@file:Suppress("unused", "MemberVisibilityCanBePrivate")

package ch.digorydoo.kutils.cjk

fun kanaToRomaji(kana: String): String {
    var result = ""
    var last = ""
    var i = 0

    while (i < kana.length) {
        var append: String

        val c4 = if (i < kana.length - 3) kana.slice(i .. i + 3) else ""
        val quad = quadrigraphToRomaji(c4)

        if (quad != null) {
            append = quad
            i += 4
        } else {
            val c3 = if (i < kana.length - 2) kana.slice(i .. i + 2) else ""
            val tri = trigraphToRomaji(c3)

            if (tri != null) {
                append = tri
                i += 3
            } else {
                val c2 = if (i < kana.length - 1) kana.slice(i .. i + 1) else ""
                val di = digraphToRomaji(c2)

                if (di != null) {
                    append = di
                    i += 2
                } else {
                    val c1 = kana[i++]
                    val mono = monographToRomaji(c1)

                    append = if (mono == null) {
                        "$c1"
                    } else if (last == "n") {
                        val needsQuote = when (mono) {
                            "a" -> true
                            "i" -> true
                            "u" -> true
                            "e" -> true
                            "o" -> true
                            else -> false
                        }

                        if (needsQuote) {
                            "'${mono}"
                        } else {
                            mono
                        }
                    } else {
                        mono
                    }
                }
            }
        }

        if (append.isEmpty()) {
            throw RuntimeException("Nothing to append!")
        }

        result += append
        last = append
    }

    return result
}

private fun quadrigraphToRomaji(quad: String): String? {
    return when (quad) {
        // Hiragana digraphs with small tsu and long vowel
        "っきゃあ" -> "kkyā"
        "っきゅう" -> "kkyū"
        "っきょう" -> "kkyō"
        "っしゃあ" -> "sshā"
        "っしゅう" -> "sshū"
        "っしょう" -> "sshō"
        "っちゃあ" -> "cchā"
        "っちゅう" -> "cchū"
        "っちょう" -> "cchō"
        "っぴょう" -> "ppyō"
        else -> null
    }
}

private fun trigraphToRomaji(tri: String): String? {
    return when (tri) {
        // Hiragana digraphs with long vowel
        "きゃあ" -> "kyā"
        "きゅう" -> "kyū"
        "きょう" -> "kyō"
        "しゃあ" -> "shā"
        "しゅう" -> "shū"
        "しょう" -> "shō"
        "ちゃあ" -> "chā"
        "ちゅう" -> "chū"
        "ちょう" -> "chō"
        "にゃあ" -> "nyā"
        "にゅう" -> "nyū"
        "にょう" -> "nyō"
        "ひゃあ" -> "hyā"
        "ひゅう" -> "hyū"
        "ひょう" -> "hyō"
        "みゃあ" -> "myā"
        "みゅう" -> "myū"
        "みょう" -> "myō"
        "りゃあ" -> "ryā"
        "りゅう" -> "ryū"
        "りょう" -> "ryō"
        // Hiragana dakuten digraphs with long vowel
        "ぎゃあ" -> "gyā"
        "ぎゅう" -> "gyū"
        "ぎょう" -> "gyō"
        "じゃあ" -> "jā"
        "じゅう" -> "jū"
        "じょう" -> "jō"
        "ぢゃあ" -> "djā"
        "ぢゅう" -> "djū"
        "ぢょう" -> "djō"
        "びゃあ" -> "byā"
        "びゅう" -> "byū"
        "びょう" -> "byō"
        // Hiragana handakuten digraphs with long vowel
        "ぴゃあ" -> "pyā"
        "ぴゅう" -> "pyū"
        "ぴょう" -> "pyō"
        // Hiragana digraphs with small tsu
        "っきゃ" -> "kkya"
        "っきゅ" -> "kkyu"
        "っきょ" -> "kkyo"
        "っしゃ" -> "ssha"
        "っしゅ" -> "sshu"
        "っしょ" -> "ssho"
        "っちゃ" -> "ccha"
        "っちゅ" -> "cchu"
        "っちょ" -> "ccho"
        "っぴゃ" -> "ppya"
        // Hiragana monographs with long vowel and small tsu
        "っかあ" -> "kkā"
        "っきい" -> "kkī"
        "っくう" -> "kkū"
        "っけえ" -> "kkē"
        "っこう" -> "kkō"
        "っさあ" -> "ssā"
        "っしい" -> "sshī"
        "っすう" -> "ssū"
        "っせえ" -> "ssē"
        "っそう" -> "ssō"
        "ったあ" -> "ttā"
        "っちい" -> "cchī"
        "っつう" -> "ttsū"
        "ってえ" -> "ttē"
        "っとう" -> "ttō"
        "っまあ" -> "mmā"
        "っみい" -> "mmī"
        "っむう" -> "mmū"
        "っめえ" -> "mmē"
        "っもう" -> "mmō"
        // Hiragana dakuten monographs with long vowel and small tsu
        "っざあ" -> "zzā"
        "っずう" -> "zzū"
        "っぜえ" -> "zzē"
        "っぞう" -> "zzō"
        "っだあ" -> "ddā"
        "っぢい" -> "ddzī"
        "っづう" -> "ddzū"
        "っでえ" -> "ddē"
        "っどう" -> "ddō"
        "っばあ" -> "bbā"
        "っびい" -> "bbī"
        "っぶう" -> "bbū"
        "っべえ" -> "bbē"
        "っぼう" -> "bbō"
        // Hiragana handakuten monographs with long vowel and small tsu
        "っぱあ" -> "ppā"
        "っぴい" -> "ppī"
        "っぷう" -> "ppū"
        "っぺえ" -> "ppē"
        "っぽう" -> "ppō"
        // Katakana digraphs with long vowel
        "キャー" -> "kyā"
        "キュウ" -> "kyū"
        "キュー" -> "kyū"
        "キョウ" -> "kyō"
        "キョー" -> "kyō"
        "シャー" -> "shā"
        "シュウ" -> "shū"
        "シュー" -> "shū"
        "ショウ" -> "shō"
        "ショー" -> "shō"
        "チャー" -> "chā"
        "チュウ" -> "chū"
        "チュー" -> "chū"
        "チョウ" -> "chō"
        "チョー" -> "chō"
        "ティー" -> "tī"
        "ニャー" -> "nyā"
        "ニュウ" -> "nyū"
        "ニュー" -> "nyū"
        "ニョウ" -> "nyō"
        "ニョー" -> "nyō"
        "ヒャー" -> "hyā"
        "ヒュウ" -> "hyū"
        "ヒュー" -> "hyū"
        "ヒョウ" -> "hyō"
        "ヒョー" -> "hyō"
        "フェー" -> "fē"
        "フォウ" -> "fō"
        "フォー" -> "fō"
        "ミャー" -> "myā"
        "ミュウ" -> "myū"
        "ミュー" -> "myū"
        "ミョウ" -> "myō"
        "ミョー" -> "myō"
        "リャー" -> "ryā"
        "リュウ" -> "ryū"
        "リュー" -> "ryū"
        "リョウ" -> "ryō"
        "リョー" -> "ryō"
        // Katakana dakuten digraphs with long vowel
        "ギャー" -> "gyā"
        "ギュウ" -> "gyū"
        "ギュー" -> "gyū"
        "ギョウ" -> "gyō"
        "ギョー" -> "gyō"
        "ジャー" -> "jā"
        "ジュウ" -> "jū"
        "ジュー" -> "jū"
        "ジョウ" -> "jō"
        "ジョー" -> "jō"
        "ヂャー" -> "djā"
        "ヂュウ" -> "djū"
        "ヂュー" -> "djū"
        "ヂョウ" -> "djō"
        "ヂョー" -> "djō"
        "ディー" -> "dī"
        "ビャー" -> "byā"
        "ビュウ" -> "byū"
        "ビュー" -> "byū"
        "ビョウ" -> "byō"
        "ビョー" -> "byō"
        // Katakana handakuten digraphs with long vowel
        "ピャー" -> "pyā"
        "ピュウ" -> "pyū"
        "ピュー" -> "pyū"
        "ピョウ" -> "pyō"
        "ピョー" -> "pyō"
        // Katakana digraphs with small tsu
        "ッキャ" -> "kkya"
        "ッキュ" -> "kkyu"
        "ッキョ" -> "kkyo"
        "ッシャ" -> "ssha"
        "ッシュ" -> "sshu"
        "ッショ" -> "ssho"
        "ッチャ" -> "ccha"
        "ッチュ" -> "cchu"
        "ッチョ" -> "ccho"
        "ッツェ" -> "ttse"
        // Katakana monographs with long vowel and small tsu
        "ッカー" -> "kkā"
        "ッキー" -> "kkī"
        "ックー" -> "kkū"
        "ッケー" -> "kkē"
        "ッコー" -> "kkō"
        "ッサー" -> "ssā"
        "ッシー" -> "sshī"
        "ッスー" -> "ssū"
        "ッセー" -> "ssē"
        "ッソー" -> "ssō"
        "ッター" -> "ttā"
        "ッチー" -> "cchī"
        "ッツー" -> "ttsū"
        "ッテー" -> "ttē"
        "ットー" -> "ttō"
        "ッホー" -> "hhō"
        "ッマー" -> "mmā"
        "ッミー" -> "mmī"
        "ッムー" -> "mmū"
        "ッメー" -> "mmē"
        "ッモー" -> "mmō"
        // Katakana dakuten monographs with long vowel and small tsu
        "ッザー" -> "zzā"
        "ッズー" -> "zzū"
        "ッゼー" -> "zzē"
        "ッゾー" -> "zzō"
        "ッダー" -> "ddā"
        "ッヂー" -> "ddzī"
        "ッヅー" -> "ddzū"
        "ッデー" -> "ddē"
        "ッドー" -> "ddō"
        "ッバー" -> "bbā"
        "ッビー" -> "bbī"
        "ッブー" -> "bbū"
        "ッベー" -> "bbē"
        "ッボー" -> "bbō"
        // Katakana handakuten monographs with long vowel and small tsu
        "ッパー" -> "ppā"
        "ッピー" -> "ppī"
        "ップー" -> "ppū"
        "ッペー" -> "ppē"
        "ッポー" -> "ppō"
        // Punctuation
        "・・・" -> "…"
        "···" -> "…"
        else -> null
    }
}

private fun digraphToRomaji(di: String): String? {
    return when (di) {
        // Hiragana digraphs
        "きゃ" -> "kya"
        "きゅ" -> "kyu"
        "きょ" -> "kyo"
        "しゃ" -> "sha"
        "しゅ" -> "shu"
        "しょ" -> "sho"
        "ちぇ" -> "che"
        "ちゃ" -> "cha"
        "ちゅ" -> "chu"
        "ちょ" -> "cho"
        "にゃ" -> "nya"
        "にゅ" -> "nyu"
        "にょ" -> "nyo"
        "ひゃ" -> "hya"
        "ひゅ" -> "hyu"
        "ひょ" -> "hyo"
        "ふぁ" -> "fa"
        "ふぃ" -> "fi"
        "ふぇ" -> "fe"
        "ふぉ" -> "fo"
        "みゃ" -> "mya"
        "みゅ" -> "myu"
        "みょ" -> "myo"
        "りゃ" -> "rya"
        "りゅ" -> "ryu"
        "りょ" -> "ryo"
        // Hiragana dakuten digraphs
        "ぎゃ" -> "gya"
        "ぎゅ" -> "gyu"
        "ぎょ" -> "gyo"
        "じゃ" -> "ja"
        "じゅ" -> "ju"
        "じょ" -> "jo"
        "ぢゃ" -> "dja"
        "ぢゅ" -> "dju"
        "ぢょ" -> "djo"
        "びゃ" -> "bya"
        "びゅ" -> "byu"
        "びょ" -> "byo"
        // Hiragana handakuten digraphs
        "ぴゃ" -> "pya"
        "ぴゅ" -> "pyu"
        "ぴょ" -> "pyo"
        // Hiragana tsu
        "っか" -> "kka"
        "っが" -> "gga"
        "っき" -> "kki"
        "っぎ" -> "ggi"
        "っく" -> "kku"
        "っぐ" -> "ggu"
        "っけ" -> "kke"
        "っげ" -> "gge"
        "っこ" -> "kko"
        "っご" -> "ggo"
        "っさ" -> "ssa"
        "っし" -> "sshi"
        "っす" -> "ssu"
        "っせ" -> "sse"
        "っそ" -> "sso"
        "った" -> "tta"
        "っち" -> "cchi"
        "っつ" -> "ttsu"
        "って" -> "tte"
        "っと" -> "tto"
        "っど" -> "ddo"
        // Hiragana handakuten with small tsu
        "っぱ" -> "ppa"
        "っぴ" -> "ppi"
        "っぷ" -> "ppu"
        "っぺ" -> "ppe"
        "っぽ" -> "ppo"
        // Hiragana long vowels
        "あぁ" -> "ā"
        "いぃ" -> "ī"
        "うぅ" -> "ū"
        "えぇ" -> "ē"
        "おう" -> "ō"
        "おぉ" -> "ō"
        "おお" -> "ō"
        "かあ" -> "kā"
        "きい" -> "kī"
        "くう" -> "kū"
        "けえ" -> "kē"
        "こう" -> "kō"
        "こお" -> "kō"
        "さあ" -> "sā"
        "しい" -> "shī"
        "すう" -> "sū"
        "せえ" -> "sē"
        "そう" -> "sō"
        "たあ" -> "tā"
        "ちい" -> "chī"
        "つう" -> "tsū"
        "てえ" -> "tē"
        "とう" -> "tō"
        "とお" -> "tō"
        "なあ" -> "nā"
        "にい" -> "nī"
        "ぬう" -> "nū"
        "ねえ" -> "nē"
        "のう" -> "nō"
        "のお" -> "nō"
        "はあ" -> "hā"
        "ひい" -> "hī"
        "ふう" -> "fū"
        "へえ" -> "hē"
        "ほう" -> "hō"
        "ほお" -> "hō"
        "まあ" -> "mā"
        "みい" -> "mī"
        "むう" -> "mū"
        "めえ" -> "mē"
        "もう" -> "mō"
        "やあ" -> "yā"
        "ゆう" -> "yū"
        "よう" -> "yō"
        "よお" -> "yō"
        "らあ" -> "rā"
        "りい" -> "rī"
        "るう" -> "rū"
        "れえ" -> "rē"
        "ろう" -> "rō"
        "わあ" -> "wā"
        // Hiragana dakuten with long vowels
        "があ" -> "gā"
        "ぎい" -> "gī"
        "ぐう" -> "gū"
        "げえ" -> "gē"
        "ごう" -> "gō"
        "ざあ" -> "zā"
        "じい" -> "jī"
        "ずう" -> "zū"
        "ぜえ" -> "zē"
        "ぞう" -> "zō"
        "だあ" -> "dā"
        "ぢい" -> "dzī"
        "づう" -> "dzū"
        "でえ" -> "dē"
        "どう" -> "dō"
        "どお" -> "dō"
        "ばあ" -> "bā"
        "びい" -> "bī"
        "ぶう" -> "bū"
        "べえ" -> "bē"
        "ぼう" -> "bō"
        // Hiragana handakuten with long vowels
        "ぱあ" -> "pā"
        "ぴい" -> "pī"
        "ぷう" -> "pū"
        "ぺえ" -> "pē"
        "ぽう" -> "pō"
        // Katakana digraphs
        "キャ" -> "kya"
        "キュ" -> "kyu"
        "キョ" -> "kyo"
        "シャ" -> "sha"
        "シュ" -> "shu"
        "ショ" -> "sho"
        "チェ" -> "che"
        "チャ" -> "cha"
        "チュ" -> "chu"
        "チョ" -> "cho"
        "ティ" -> "ti"
        "ニャ" -> "nya"
        "ニュ" -> "nyu"
        "ニョ" -> "nyo"
        "ヒャ" -> "hya"
        "ヒュ" -> "hyu"
        "ヒョ" -> "hyo"
        "ファ" -> "fa"
        "フィ" -> "fi"
        "フェ" -> "fe"
        "フォ" -> "fo"
        "ミャ" -> "mya"
        "ミュ" -> "myu"
        "ミョ" -> "myo"
        "リャ" -> "rya"
        "リュ" -> "ryu"
        "リョ" -> "ryo"
        // Katakana dakuten digraphs
        "ギャ" -> "gya"
        "ギュ" -> "gyu"
        "ギョ" -> "gyo"
        "ジェ" -> "je"
        "ジャ" -> "ja"
        "ジュ" -> "ju"
        "ジョ" -> "jo"
        "ヂァ" -> "dja"
        "ヂゥ" -> "dju"
        "ヂォ" -> "djo"
        "ディ" -> "di"
        "ビャ" -> "bya"
        "ビュ" -> "byu"
        "ビョ" -> "byo"
        // Katakana handakuten digraphs
        "ピャ" -> "pya"
        "ピュ" -> "pyu"
        "ピョ" -> "pyo"
        // Katakana tsu
        "ッカ" -> "kka"
        "ッガ" -> "gga"
        "ッキ" -> "kki"
        "ッギ" -> "ggi"
        "ック" -> "kku"
        "ッグ" -> "ggu"
        "ッケ" -> "kke"
        "ッゲ" -> "gge"
        "ッコ" -> "kko"
        "ッゴ" -> "ggo"
        "ッサ" -> "ssa"
        "ッシ" -> "sshi"
        "ッジ" -> "tji"
        "ッス" -> "ssu"
        "ッセ" -> "sse"
        "ッソ" -> "sso"
        "ッタ" -> "tta"
        "ッチ" -> "cchi"
        "ッツ" -> "ttsu"
        "ッテ" -> "tte"
        "ット" -> "tto"
        "ッド" -> "ddo"
        "ッホ" -> "hho"
        // Katakana handakuten with small tsu
        "ッパ" -> "ppa"
        "ッピ" -> "ppi"
        "ップ" -> "ppu"
        "ッペ" -> "ppe"
        "ッポ" -> "ppo"
        // Katakana long vowels
        "アー" -> "ā"
        "イー" -> "ī"
        "ウー" -> "ū"
        "エー" -> "ē"
        "オー" -> "ō"
        "カー" -> "kā"
        "キー" -> "kī"
        "クー" -> "kū"
        "ケー" -> "kē"
        "コウ" -> "kō"
        "コー" -> "kō"
        "サー" -> "sā"
        "シー" -> "shī"
        "スー" -> "sū"
        "セー" -> "sē"
        "ソー" -> "sō"
        "ター" -> "tā"
        "チー" -> "chī"
        "ツー" -> "tsū"
        "テー" -> "tē"
        "トー" -> "tō"
        "ナー" -> "nā"
        "ニー" -> "nī"
        "ヌー" -> "nū"
        "ネー" -> "nē"
        "ノー" -> "nō"
        "ハー" -> "hā"
        "ヒー" -> "hī"
        "フー" -> "fū"
        "ヘー" -> "hē"
        "ホオ" -> "hō"
        "ホー" -> "hō"
        "マー" -> "mā"
        "ミー" -> "mī"
        "ムー" -> "mū"
        "メー" -> "mē"
        "モー" -> "mō"
        "ヤー" -> "yā"
        "ユー" -> "yū"
        "ヨー" -> "yō"
        "ラー" -> "rā"
        "リー" -> "rī"
        "ルー" -> "rū"
        "レー" -> "rē"
        "ロー" -> "rō"
        "ワー" -> "wā"
        // Katakana dakuten with long vowels
        "ガー" -> "gā"
        "ギー" -> "gī"
        "グー" -> "gū"
        "ゲー" -> "gē"
        "ゴー" -> "gō"
        "ザー" -> "zā"
        "ジー" -> "jī"
        "ズー" -> "zū"
        "ゼー" -> "zē"
        "ゾー" -> "zō"
        "ダー" -> "dā"
        "ヂー" -> "dzī"
        "ヅー" -> "dzū"
        "デー" -> "dē"
        "ドウ" -> "dō"
        "ドー" -> "dō"
        "バー" -> "bā"
        "ビー" -> "bī"
        "ブー" -> "bū"
        "ベー" -> "bē"
        "ボー" -> "bō"
        // Katakana handakuten with long vowels
        "パー" -> "pā"
        "ピー" -> "pī"
        "プー" -> "pū"
        "ペー" -> "pē"
        "ポー" -> "pō"
        else -> null
    }
}

private fun monographToRomaji(mono: Char): String? {
    return when (mono) {
        // Hiragana monographs
        'あ' -> "a"
        'い' -> "i"
        'う' -> "u"
        'え' -> "e"
        'お' -> "o"
        'か' -> "ka"
        'き' -> "ki"
        'く' -> "ku"
        'け' -> "ke"
        'こ' -> "ko"
        'さ' -> "sa"
        'し' -> "shi"
        'す' -> "su"
        'せ' -> "se"
        'そ' -> "so"
        'た' -> "ta"
        'ち' -> "chi"
        'つ' -> "tsu"
        'て' -> "te"
        'と' -> "to"
        'な' -> "na"
        'に' -> "ni"
        'ぬ' -> "nu"
        'ね' -> "ne"
        'の' -> "no"
        'は' -> "ha"
        'ひ' -> "hi"
        'ふ' -> "fu"
        'へ' -> "he"
        'ほ' -> "ho"
        'ま' -> "ma"
        'み' -> "mi"
        'む' -> "mu"
        'め' -> "me"
        'も' -> "mo"
        'や' -> "ya"
        'ゆ' -> "yu"
        'よ' -> "yo"
        'ら' -> "ra"
        'り' -> "ri"
        'る' -> "ru"
        'れ' -> "re"
        'ろ' -> "ro"
        'わ' -> "wa"
        'を' -> "o"
        'ん' -> "n"
        // Hiragana dakuten
        'が' -> "ga"
        'ぎ' -> "gi"
        'ぐ' -> "gu"
        'げ' -> "ge"
        'ご' -> "go"
        'ざ' -> "za"
        'じ' -> "ji"
        'ず' -> "zu"
        'ぜ' -> "ze"
        'ぞ' -> "zo"
        'だ' -> "da"
        'ぢ' -> "dzi"
        'づ' -> "dzu"
        'で' -> "de"
        'ど' -> "do"
        'ば' -> "ba"
        'び' -> "bi"
        'ぶ' -> "bu"
        'べ' -> "be"
        'ぼ' -> "bo"
        // Hiragana handakuten
        'ぱ' -> "pa"
        'ぴ' -> "pi"
        'ぷ' -> "pu"
        'ぺ' -> "pe"
        'ぽ' -> "po"
        // Hiragana small monographs
        'ぁ' -> "a"
        'ぃ' -> "i"
        'ぅ' -> "u"
        'ぇ' -> "e"
        'ぉ' -> "o"
        'ゃ' -> "ya"
        'ゅ' -> "yu"
        'ょ' -> "yo"
        // Katakana monographs
        'ア' -> "a"
        'イ' -> "i"
        'ウ' -> "u"
        'エ' -> "e"
        'オ' -> "o"
        'カ' -> "ka"
        'キ' -> "ki"
        'ク' -> "ku"
        'ケ' -> "ke"
        'コ' -> "ko"
        'サ' -> "sa"
        'シ' -> "shi"
        'ス' -> "su"
        'セ' -> "se"
        'ソ' -> "so"
        'タ' -> "ta"
        'チ' -> "chi"
        'ツ' -> "tsu"
        'テ' -> "te"
        'ト' -> "to"
        'ナ' -> "na"
        'ニ' -> "ni"
        'ヌ' -> "nu"
        'ネ' -> "ne"
        'ノ' -> "no"
        'ハ' -> "ha"
        'ヒ' -> "hi"
        'フ' -> "fu"
        'ヘ' -> "he"
        'ホ' -> "ho"
        'マ' -> "ma"
        'ミ' -> "mi"
        'ム' -> "mu"
        'メ' -> "me"
        'モ' -> "mo"
        'ヤ' -> "ya"
        'ユ' -> "yu"
        'ヨ' -> "yo"
        'ラ' -> "ra"
        'リ' -> "ri"
        'ル' -> "ru"
        'レ' -> "re"
        'ロ' -> "ro"
        'ワ' -> "wa"
        'ヲ' -> "wo"
        'ン' -> "n"
        // Katakana dakuten
        'ガ' -> "ga"
        'ギ' -> "gi"
        'グ' -> "gu"
        'ゲ' -> "ge"
        'ゴ' -> "go"
        'ザ' -> "za"
        'ジ' -> "ji"
        'ズ' -> "zu"
        'ゼ' -> "ze"
        'ゾ' -> "zo"
        'ダ' -> "da"
        'ヂ' -> "dzi"
        'ヅ' -> "dzu"
        'デ' -> "de"
        'ド' -> "do"
        'バ' -> "ba"
        'ビ' -> "bi"
        'ブ' -> "bu"
        'ベ' -> "be"
        'ボ' -> "bo"
        // Katakana handakuten
        'パ' -> "pa"
        'ピ' -> "pi"
        'プ' -> "pu"
        'ペ' -> "pe"
        'ポ' -> "po"
        // Katakana small monographs
        'ァ' -> "a"
        'ィ' -> "i"
        'ゥ' -> "u"
        'ェ' -> "e"
        'ォ' -> "o"
        'ャ' -> "ya"
        'ュ' -> "yu"
        'ョ' -> "yo"
        // Full-width numbers
        '０' -> "0"
        '１' -> "1"
        '２' -> "2"
        '３' -> "3"
        '４' -> "4"
        '５' -> "5"
        '６' -> "6"
        '７' -> "7"
        '８' -> "8"
        '９' -> "9"
        // Kanji numbers
        '一' -> "1"
        '二' -> "2"
        '三' -> "3"
        '四' -> "4"
        '五' -> "5"
        '六' -> "6"
        '七' -> "7"
        '八' -> "8"
        '九' -> "9"
        '十' -> "10"
        // Punctuation
        '、' -> ","
        '。' -> "."
        '！' -> "!"
        '：' -> ":"
        '；' -> ";"
        '？' -> "?"
        '〜' -> "~" // U+301C wave dash
        '～' -> "~" // U+FF5E full-width tilde
        '・' -> " / "
        '　' -> " "
        '「' -> "‘" // U+2018 left single quotation mark
        '」' -> "’" // U+2019 right single quotation mark
        '『' -> "“" // U+201C left double quotation mark
        '』' -> "”" // U+201D right double quotation mark
        else -> null
    }
}
